/-
SPDX-FileCopyrightText: 2026 Sanjit Singh Mehat
SPDX-License-Identifier: Apache-2.0

Native result packaging for the verified TrackB reachability kernel.

Search and safety theorems remain metadata-free.  This module is the separate
adapter boundary that turns semantic traces and closure certificates into
native JSON-shaped results, and then requires the ordinary executable checker
to accept the generated bytes before they can leave the process.
-/

import TrackBReplay

namespace TrackBReplay

open Lean

def globalSafetyClaimBoundary : String :=
  "GLOBALLY_SAFE means every state reachable in the exact closed TrackB Boolean " ++
  "workflow model is non-forbidden. It does not prove safety of undeclared " ++
  "runtime behavior, external systems, or the real world."

def safeWithinBoundClaimBoundary : String :=
  "SAFE_WITHIN_BOUND means no bad replay exists at or below the configured " ++
  "bound in the exact TrackB Boolean workflow model. It does not prove " ++
  "global safety or safety of undeclared runtime behavior."

structure BoundedSafetyResult where
  workflow : String
  schemaVersion : String
  bound : Nat
  status : String
  visited : List BoolMap
  frontier : List BoolMap
  claimBoundary : String
  deriving Repr, DecidableEq

def makeBoundedSafetyResult
    (workflow : Workflow)
    (visited frontier : List (KernelState workflow.variables.length)) :
    BoundedSafetyResult :=
  {
    workflow := workflow.name
    schemaVersion := workflow.schemaVersion
    bound := workflow.bound
    status := "SAFE_WITHIN_BOUND"
    visited := visited.map
      (KernelState.toBoolMap workflow.variables)
    frontier := frontier.map
      (KernelState.toBoolMap workflow.variables)
    claimBoundary := safeWithinBoundClaimBoundary
  }

structure GlobalSafetyResult where
  workflow : String
  schemaVersion : String
  bound : Nat
  status : String
  closure : List BoolMap
  claimBoundary : String
  deriving Repr, DecidableEq

/--
All-depth safety of a successfully compiled workflow.  The existential compile
witness keeps malformed native inputs outside the proposition rather than
making the implication vacuously true when compilation fails.
-/
def Workflow.GloballySafe (workflow : Workflow) : Prop :=
  ∃ kernel : Kernel workflow.variables.length,
    workflow.compile = .ok kernel ∧
    ∀ state, kernel.Reachable state → ¬kernel.Forbidden state

def GlobalSafetyResult.metadataCheck
    (workflow : Workflow)
    (result : GlobalSafetyResult) : Bool :=
  workflow.WellFormed &&
  result.workflow == workflow.name &&
  result.schemaVersion == workflow.schemaVersion &&
  result.bound == workflow.bound &&
  result.status == "GLOBALLY_SAFE" &&
  result.claimBoundary == globalSafetyClaimBoundary

def GlobalSafetyResult.semanticCheck
    (workflow : Workflow)
    (result : GlobalSafetyResult) : Bool :=
  result.closure.all (State.WellFormed workflow) &&
  match workflow.compile with
  | .error _ => false
  | .ok kernel =>
      let certificate :=
        result.closure.map
          (BoolMap.toKernelState workflow.variables)
      SafetyCertificate.check kernel certificate

def GlobalSafetyResult.check
    (workflow : Workflow)
    (result : GlobalSafetyResult) : Bool :=
  result.metadataCheck workflow &&
  result.semanticCheck workflow

/--
A native global-safety result accepted by the executable checker entails the
unbounded reachability proposition over the one frozen kernel.
-/
theorem GlobalSafetyResult.check_sound
    {workflow : Workflow}
    {result : GlobalSafetyResult}
    (hcheck : result.check workflow = true) :
    workflow.GloballySafe := by
  unfold GlobalSafetyResult.check at hcheck
  simp only [Bool.and_eq_true] at hcheck
  have hsemantic := hcheck.2
  unfold GlobalSafetyResult.semanticCheck at hsemantic
  cases hcompile : workflow.compile with
  | error message =>
      simp [hcompile] at hsemantic
  | ok kernel =>
      rw [hcompile] at hsemantic
      simp only [Bool.and_eq_true] at hsemantic
      have hcertificate :
          SafetyCertificate.check kernel
            (result.closure.map
              (BoolMap.toKernelState workflow.variables)) = true := by
        exact hsemantic.2
      exact ⟨
        kernel,
        hcompile,
        SafetyCertificate.check_sound hcertificate
      ⟩

def SemanticTrace.toNativeSteps
    (workflow : Workflow) :
    SemanticTrace workflow.variables.length → List TraceStep
  | .initial state =>
      [{
        step := 0
        action := none
        stateBefore := none
        stateDelta := []
        stateAfter := state.toBoolMap workflow.variables
      }]
  | .step prior actionName after =>
      let beforeMap :=
        prior.finalState.toBoolMap workflow.variables
      let afterMap :=
        after.toBoolMap workflow.variables
      prior.toNativeSteps workflow ++ [{
        step := prior.actionCount + 1
        action := some actionName
        stateBefore := some beforeMap
        stateDelta := beforeMap.delta afterMap
        stateAfter := afterMap
      }]

def SemanticTrace.toUnsafeResult
    (workflow : Workflow)
    (trace : SemanticTrace workflow.variables.length) : UnsafeResult :=
  {
    workflow := workflow.name
    schemaVersion := workflow.schemaVersion
    bound := workflow.bound
    status := "UNSAFE"
    violation := {
      condition := workflow.forbidden
      firstBadStep := trace.actionCount
    }
    trace := trace.toNativeSteps workflow
    claimBoundary := unsafeClaimBoundary
  }

/--
The generated result is proof-carrying with respect to the existing native
counterexample checker.  Packaging fails closed if any adapter obligation is
not accepted.
-/
structure CheckedGeneratedUnsafe
    (workflow : Workflow)
    (trace : SemanticTrace workflow.variables.length) where
  result : UnsafeResult
  generated : result = trace.toUnsafeResult workflow
  accepted : check workflow result = true

def packageGeneratedUnsafe
    (workflow : Workflow)
    (trace : SemanticTrace workflow.variables.length) :
    Except String (CheckedGeneratedUnsafe workflow trace) :=
  let result := trace.toUnsafeResult workflow
  if accepted : check workflow result = true then
    .ok { result, generated := rfl, accepted }
  else
    .error
      "semantic counterexample could not be packaged as a checker-accepted native result"

def makeGlobalSafetyResult
    (workflow : Workflow)
    (closure : SafetyCertificate workflow.variables.length) :
    GlobalSafetyResult :=
  {
    workflow := workflow.name
    schemaVersion := workflow.schemaVersion
    bound := workflow.bound
    status := "GLOBALLY_SAFE"
    closure :=
      closure.map
        (KernelState.toBoolMap workflow.variables)
    claimBoundary := globalSafetyClaimBoundary
  }

structure CheckedGeneratedGlobalSafety
    (workflow : Workflow)
    (closure : SafetyCertificate workflow.variables.length) where
  result : GlobalSafetyResult
  generated : result = makeGlobalSafetyResult workflow closure
  accepted : result.check workflow = true

def packageGeneratedGlobalSafety
    (workflow : Workflow)
    (closure : SafetyCertificate workflow.variables.length) :
    Except String (CheckedGeneratedGlobalSafety workflow closure) :=
  let result := makeGlobalSafetyResult workflow closure
  if accepted : result.check workflow = true then
    .ok { result, generated := rfl, accepted }
  else
    .error
      "kernel closure could not be packaged as a checker-accepted global-safety result"

theorem generated_global_result_is_globally_safe
    {workflow : Workflow}
    {closure : SafetyCertificate workflow.variables.length}
    (generated : CheckedGeneratedGlobalSafety workflow closure) :
    workflow.GloballySafe :=
  GlobalSafetyResult.check_sound generated.accepted

/--
A compiled workflow packages the exact kernel together with the equality that
binds it to the validated native workflow.
-/
structure CompiledWorkflow (workflow : Workflow) where
  kernel : Kernel workflow.variables.length
  compiled : workflow.compile = .ok kernel

def Workflow.compileChecked
    (workflow : Workflow) : Except String (CompiledWorkflow workflow) :=
  match hcompile : workflow.compile with
  | .error message => .error message
  | .ok kernel => .ok { kernel, compiled := hcompile }

/--
The exact native bounded-safety artifact, the engine outcome that produced its
state lists, and the semantic no-counterexample theorem travel as one value.
The executable can therefore emit only `result`; it never reconstructs an
artifact after discarding the proof-bearing outcome.
-/
structure CheckedGeneratedBoundedSafety
    (workflow : Workflow)
    (compiled : CompiledWorkflow workflow) where
  visited : List (KernelState workflow.variables.length)
  frontier : List (KernelState workflow.variables.length)
  result : BoundedSafetyResult
  engine :
    reachabilityEngine compiled.kernel workflow.bound =
      .safeWithinBound visited frontier
  generated :
    result = makeBoundedSafetyResult workflow visited frontier
  semantic :
    ¬∃ trace,
      BoundedCounterexample compiled.kernel workflow.bound trace

def packageGeneratedBoundedSafety
    (workflow : Workflow)
    (compiled : CompiledWorkflow workflow)
    (visited frontier : List (KernelState workflow.variables.length))
    (engine :
      reachabilityEngine compiled.kernel workflow.bound =
        .safeWithinBound visited frontier) :
    CheckedGeneratedBoundedSafety workflow compiled :=
  {
    visited
    frontier
    result := makeBoundedSafetyResult workflow visited frontier
    engine
    generated := rfl
    semantic := reachabilityEngine_safeWithinBound_sound engine
  }

/--
Proof-carrying result lattice used by the executable.  Every successful
constructor carries the theorem appropriate to its status, and every emitted
native artifact is definitionally bound to the semantic certificate that
produced it.
-/
inductive CheckedReachability
    (workflow : Workflow)
    (compiled : CompiledWorkflow workflow) where
  | counterexample
      (trace : SemanticTrace workflow.variables.length)
      (semantic :
        BoundedCounterexample
          compiled.kernel workflow.bound trace)
      (native : CheckedGeneratedUnsafe workflow trace)
  | safeWithinBound
      (native : CheckedGeneratedBoundedSafety workflow compiled)
  | globallySafe
      (closure : SafetyCertificate workflow.variables.length)
      (semantic :
        ∀ state,
          compiled.kernel.Reachable state →
          ¬compiled.kernel.Forbidden state)
      (native : CheckedGeneratedGlobalSafety workflow closure)

def runCheckedReachability
    (workflow : Workflow)
    (compiled : CompiledWorkflow workflow) :
    Except String (CheckedReachability workflow compiled) :=
  match hengine :
      reachabilityEngine compiled.kernel workflow.bound with
  | .unsafeFound trace =>
      match packageGeneratedUnsafe workflow trace with
      | .error message => .error message
      | .ok native =>
          .ok <| .counterexample trace
            (reachabilityEngine_unsafe_sound hengine)
            native
  | .safeWithinBound visited frontier =>
      .ok <| .safeWithinBound <|
        packageGeneratedBoundedSafety
          workflow compiled visited frontier hengine
  | .globallySafe closure =>
      match packageGeneratedGlobalSafety workflow closure with
      | .error message => .error message
      | .ok native =>
          .ok <| .globallySafe closure
            (reachabilityEngine_globallySafe_sound hengine)
            native
  | .error message => .error message

def EndToEndUnsafe
    (workflow : Workflow)
    (compiled : CompiledWorkflow workflow)
    (result : UnsafeResult) : Prop :=
  ∃ trace,
    BoundedCounterexample
      compiled.kernel workflow.bound trace ∧
    result = trace.toUnsafeResult workflow ∧
    check workflow result = true

theorem checked_unsafe_endToEnd
    {workflow : Workflow}
    {compiled : CompiledWorkflow workflow}
    {trace : SemanticTrace workflow.variables.length}
    (semantic :
      BoundedCounterexample
        compiled.kernel workflow.bound trace)
    (native : CheckedGeneratedUnsafe workflow trace) :
    EndToEndUnsafe workflow compiled native.result :=
  ⟨trace, semantic, native.generated, native.accepted⟩

def EndToEndBoundedSafety
    (workflow : Workflow)
    (compiled : CompiledWorkflow workflow)
    (result : BoundedSafetyResult) : Prop :=
  ∃ visited frontier,
    reachabilityEngine compiled.kernel workflow.bound =
      .safeWithinBound visited frontier ∧
    result = makeBoundedSafetyResult workflow visited frontier ∧
    ¬∃ trace,
      BoundedCounterexample
        compiled.kernel workflow.bound trace

theorem checked_bounded_safe_endToEnd
    {workflow : Workflow}
    {compiled : CompiledWorkflow workflow}
    (generated : CheckedGeneratedBoundedSafety workflow compiled) :
    EndToEndBoundedSafety workflow compiled generated.result :=
  ⟨
    generated.visited,
    generated.frontier,
    generated.engine,
    generated.generated,
    generated.semantic
  ⟩

def EndToEndGlobalSafety
    (workflow : Workflow)
    (result : GlobalSafetyResult) : Prop :=
  ∃ closure,
    result = makeGlobalSafetyResult workflow closure ∧
    result.check workflow = true ∧
    workflow.GloballySafe

theorem checked_global_endToEnd
    {workflow : Workflow}
    {closure : SafetyCertificate workflow.variables.length}
    (native : CheckedGeneratedGlobalSafety workflow closure) :
    EndToEndGlobalSafety workflow native.result :=
  ⟨
    closure,
    native.generated,
    native.accepted,
    GlobalSafetyResult.check_sound native.accepted
  ⟩

def boolMapToJson (mapping : BoolMap) : Json :=
  Json.mkObj <| mapping.map fun entry =>
    (entry.1, Json.bool entry.2)

def traceStepToJson (step : TraceStep) : Json :=
  Json.mkObj [
    ("step", toJson step.step),
    ("action", match step.action with
      | none => Json.null
      | some actionName => Json.str actionName),
    ("state_before", match step.stateBefore with
      | none => Json.null
      | some state => boolMapToJson state),
    ("state_delta", boolMapToJson step.stateDelta),
    ("state_after", boolMapToJson step.stateAfter)
  ]

def unsafeResultToJson (result : UnsafeResult) : Json :=
  Json.mkObj [
    ("workflow", Json.str result.workflow),
    ("schema_version", Json.str result.schemaVersion),
    ("bound", toJson result.bound),
    ("status", Json.str result.status),
    ("violation", Json.mkObj [
      ("condition", boolMapToJson result.violation.condition),
      ("first_bad_step", toJson result.violation.firstBadStep)
    ]),
    ("trace", Json.arr <|
      result.trace.map traceStepToJson |>.toArray),
    ("claim_boundary", Json.str result.claimBoundary)
  ]

def globalSafetyResultToJson (result : GlobalSafetyResult) : Json :=
  Json.mkObj [
    ("workflow", Json.str result.workflow),
    ("schema_version", Json.str result.schemaVersion),
    ("bound", toJson result.bound),
    ("status", Json.str result.status),
    ("closure", Json.arr <|
      result.closure.map boolMapToJson |>.toArray),
    ("claim_boundary", Json.str result.claimBoundary)
  ]

def boundedSafetyResultToJson (result : BoundedSafetyResult) : Json :=
  Json.mkObj [
    ("workflow", Json.str result.workflow),
    ("schema_version", Json.str result.schemaVersion),
    ("bound", toJson result.bound),
    ("status", Json.str result.status),
    ("visited", Json.arr <|
      result.visited.map boolMapToJson |>.toArray),
    ("frontier", Json.arr <|
      result.frontier.map boolMapToJson |>.toArray),
    ("claim_boundary", Json.str result.claimBoundary)
  ]

def parseGlobalSafetyResult (json : Json) :
    Except String GlobalSafetyResult := do
  requireExactObjectKeys
    "GLOBALLY_SAFE result"
    [
      "workflow",
      "schema_version",
      "bound",
      "status",
      "closure",
      "claim_boundary"
    ]
    json
  let closureJson ← json.getObjVal? "closure" >>= Json.getArr?
  return {
    workflow := ← (json.getObjVal? "workflow" >>= Json.getStr?)
    schemaVersion := ←
      (json.getObjVal? "schema_version" >>= Json.getStr?)
    bound := ← (json.getObjVal? "bound" >>= Json.getNat?)
    status := ← (json.getObjVal? "status" >>= Json.getStr?)
    closure := ← closureJson.toList.mapM
      (parseBoolMap "closure")
    claimBoundary := ←
      (json.getObjVal? "claim_boundary" >>= Json.getStr?)
  }

def parseGlobalSafetyResultText (text : String) :
    Except String GlobalSafetyResult :=
  Json.parse text >>= parseGlobalSafetyResult

end TrackBReplay
